import {app,auth,db} from './firebase-config.js';
import {onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-auth.js';
import {doc,getDoc} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js';
import {getStorage,ref,list,getDownloadURL} from 'https://www.gstatic.com/firebasejs/10.13.0/firebase-storage.js';
import {DOMAINS,classifyFilename} from './pdf-catalog.js';
const storage=getStorage(app),$=id=>document.getElementById(id);let catalog=[],groups=[],selectedFiles=[],approved=false,generation=0,mergedUrl=null,fontLevel=Number(localStorage.getItem('iBrainFontLevel')||0);
const option=(s,v,l)=>{const o=document.createElement('option');o.value=v;o.textContent=l;s.append(o)},status=t=>$('status').textContent=t;
function applyFont(){fontLevel=Math.max(-2,Math.min(5,fontLevel));document.documentElement.style.setProperty('--library-scale',1+fontLevel*.1);localStorage.setItem('iBrainFontLevel',fontLevel)}
$('fontDown').onclick=()=>{fontLevel--;applyFont()};$('fontUp').onclick=()=>{fontLevel++;applyFont()};applyFont();
async function scan(folder,res,run){let token;do{const p=await list(folder,{maxResults:100,...(token?{pageToken:token}:{})});if(run!==generation)return;for(const i of p.items)if(/\.pdf$/i.test(i.name))res.push({ref:i,name:i.name,...classifyFilename(i.name)});for(const x of p.prefixes)await scan(x,res,run);token=p.nextPageToken}while(token&&run===generation)}
function fillStars(){const s=$('stars'),d=$('domain').value;s.replaceChildren();option(s,'','난이도 선택');if(!d){s.disabled=true;return}let lv=[...new Set(catalog.filter(f=>f.domain===d).map(f=>f.stars??'unknown'))];lv.sort((a,b)=>a==='unknown'?1:b==='unknown'?-1:a-b);lv.forEach(n=>option(s,String(n),n==='unknown'?'난이도 미분류':'★'.repeat(n)));s.disabled=false;$('qty').disabled=true;$('addSet').disabled=true}
function fillQty(){const d=$('domain').value,s=$('stars').value,q=$('qty');q.replaceChildren();if(!d||!s){q.disabled=true;$('addSet').disabled=true;return}const n=catalog.filter(f=>f.domain===d&&String(f.stars??'unknown')===s).length;for(let i=1;i<=Math.min(20,n);i++)option(q,i,i+'개');q.disabled=!n;$('addSet').disabled=!n}
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function rebuild(){let used=new Set();selectedFiles=[];for(const g of groups){let c=shuffle(catalog.filter(f=>f.domain===g.domain&&String(f.stars??'unknown')===g.stars&&!used.has(f.name))).slice(0,g.count);c.forEach(f=>{used.add(f.name);selectedFiles.push(f)});g.actual=c.length}render()}
function render(){const b=$('bundle');b.replaceChildren();$('totalCount').textContent='총 '+selectedFiles.length+'개';if(!groups.length)b.innerHTML='<p class="empty">위에서 영역·난이도·개수를 선택해 추가하세요.</p>';else groups.forEach(g=>{let x=document.createElement('div');x.className='bundle-chip';x.append(document.createTextNode(g.domain+' · '+(g.stars==='unknown'?'미분류':'★'.repeat(Number(g.stars)))+' · '+(g.actual??g.count)+'개'));let z=document.createElement('button');z.textContent='×';z.onclick=()=>{groups=groups.filter(v=>v!==g);rebuild()};x.append(z);b.append(x)});$('clearBundle').disabled=$('reroll').disabled=$('makePreview').disabled=!groups.length;const p=$('previewList');p.replaceChildren();if(!selectedFiles.length)p.innerHTML='<p class="empty">아직 선택된 문제가 없습니다.</p>';else selectedFiles.forEach((f,i)=>{let x=document.createElement('div');x.className='preview-item';x.textContent=(i+1)+'. '+f.name;p.append(x)})}
async function makePreview(){if(!selectedFiles.length)return;status('통합 PDF 만드는 중…');try{const out=await PDFLib.PDFDocument.create();for(const f of selectedFiles){const u=await getDownloadURL(f.ref),buf=await(await fetch(u)).arrayBuffer(),src=await PDFLib.PDFDocument.load(buf),pages=await out.copyPages(src,src.getPageIndices());pages.forEach(p=>out.addPage(p))}const bytes=await out.save();if(mergedUrl)URL.revokeObjectURL(mergedUrl);mergedUrl=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));$('preview').src=mergedUrl;$('preview').hidden=false;$('selected').textContent='선택한 문제 '+selectedFiles.length+'개 통합 완료';$('print').disabled=$('open').disabled=false;status('PDF '+selectedFiles.length+'개 준비 완료')}catch(e){console.error(e);status('PDF를 합치지 못했습니다. Storage CORS를 확인해 주세요.')}}
async function reload(){if(!approved)return;const run=++generation;$('reload').disabled=true;status('PDF 목록을 불러오는 중…');try{let found=[];await scan(ref(storage,'evaluation-pdfs'),found,run);if(run!==generation)return;catalog=found.sort((a,b)=>a.name.localeCompare(b.name,'ko',{numeric:true}));const d=$('domain');d.replaceChildren();option(d,'','영역 선택');[...DOMAINS.map(x=>x.label),'미분류'].filter(x=>catalog.some(f=>f.domain===x)).forEach(x=>option(d,x,x));d.disabled=false;status('PDF '+catalog.length+'개 불러옴')}catch(e){console.error(e);status(e?.code==='storage/unauthorized'?'자료 접근 권한이 없습니다. Storage 규칙을 확인해 주세요.':'자료를 불러오지 못했습니다.')}finally{$('reload').disabled=false}}
$('domain').onchange=fillStars;$('stars').onchange=fillQty;$('addSet').onclick=()=>{let d=$('domain').value,s=$('stars').value,n=Number($('qty').value);if(d&&s&&n){groups.push({domain:d,stars:s,count:n});rebuild()}};$('clearBundle').onclick=()=>{groups=[];selectedFiles=[];rebuild()};$('reroll').onclick=rebuild;$('makePreview').onclick=makePreview;$('open').onclick=()=>mergedUrl&&window.open(mergedUrl,'_blank');$('print').onclick=()=>mergedUrl&&window.open(mergedUrl,'_blank');$('reload').onclick=reload;$('logoutBtn').onclick=()=>signOut(auth).then(()=>location.href='index.html');
onAuthStateChanged(auth,async user=>{const run=++generation;approved=false;$('adminLink').hidden=true;if(!user){location.href='index.html';return}try{const a=await getDoc(doc(db,'users',user.uid));if(run!==generation)return;if(!a.exists()||a.data().approved!==true){status('승인된 계정이 아닙니다.');return}approved=true;$('userEmail').textContent=user.email||'';$('adminLink').hidden=!a.data().isAdmin;await reload()}catch(e){console.error(e);status('로그인 정보 확인 중 오류가 발생했습니다.')}});
